src_dir: src
public_dir: docs

pages:
  index:
    current_check_prefix: index
    next: docs/introduction
  docs/introduction:
    title: Introduction
    link: /docs/introduction.html
    current_check_prefix: docs/introduction
    next: docs/get-mobi-css
  docs/get-mobi-css:
    title: Get Mobi.css
    link: /docs/get-mobi-css.html
    current_check_prefix: docs/get-mobi-css
    next: docs/plugins-and-themes
  docs/plugins-and-themes:
    title: Plugins and Themes
    link: /docs/plugins-and-themes.html
    current_check_prefix: docs/plugins-and-themes
    next: docs/reset
  docs/reset:
    title: Reset
    link: /docs/reset.html
    current_check_prefix: docs/reset
    next: docs/top-gap
  docs/top-gap:
    title: Top Gap
    link: /docs/top-gap.html
    current_check_prefix: docs/top-gap
    next: docs/show-hide-on-mobile
  docs/show-hide-on-mobile:
    title: Show Hide on Mobile
    link: /docs/show-hide-on-mobile.html
    current_check_prefix: docs/show-hide-on-mobile
    next: docs/flexbox
  docs/flexbox:
    title: Flexbox
    link: /docs/flexbox.html
    current_check_prefix: docs/flexbox
    next: docs/container
  docs/container:
    title: Container
    link: /docs/container.html
    current_check_prefix: docs/container
    next: docs/button
  docs/button:
    title: Button
    link: /docs/button.html
    current_check_prefix: docs/button
    next: docs/form
  docs/form:
    title: Form
    link: /docs/form.html
    current_check_prefix: docs/form
    next: docs/scroll-view
  docs/scroll-view:
    title: Scroll View
    link: /docs/scroll-view.html
    current_check_prefix: docs/scroll-view
    next: docs/table
  docs/table:
    title: Table
    link: /docs/table.html
    current_check_prefix: docs/table
    next: docs/text
  docs/text:
    title: Text
    link: /docs/text.html
    current_check_prefix: docs/text
    next: docs/build-tools
  docs/build-tools:
    title: Build Tools
    link: /docs/build-tools.html
    current_check_prefix: docs/build-tools
    next: docs/variables
  docs/variables:
    title: Variables
    link: /docs/variables.html
    current_check_prefix: docs/variables
    next: docs/create-a-plugin
  docs/create-a-plugin:
    title: Create a Plugin
    link: /docs/create-a-plugin.html
    current_check_prefix: docs/create-a-plugin
    next: docs/create-a-theme
  docs/create-a-theme:
    title: Create a Theme
    link: /docs/create-a-theme.html
    current_check_prefix: docs/create-a-theme
    next: plugins
  plugins:
    title: Plugins
    link: /plugins/index.html
    current_check_prefix: plugins
    next: themes
  themes:
    title: Themes
    link: /themes/index.html
    current_check_prefix: themes
    next: about/community
  about/community:
    title: Community
    link: /about/community.html
    current_check_prefix: about/community
    next: about/support
  about/support:
    title: Support
    link: /about/support.html
    current_check_prefix: about/support
    next: github
  github:
    title: GitHub
    link: https://github.com/mobi-css/mobi.css
  docs:
    title: Docs
    link: /docs/introduction.html
    current_check_prefix: docs
  about:
    title: About
    link: /about/community.html
    current_check_prefix: about
  docs/getting-started:
    title: Getting Started
    link: /docs/introduction.html
  docs/built-in-plugins:
    title: Built-in Plugins
    link: /docs/reset.html
  docs/customize:
    title: Customize
    link: /docs/build-tools.html
  about/index:
    title: About
    link: /about/community.html


nav:
  - id: docs
    menu:
      - id: docs/getting-started
        sub_menu:
          - id: docs/introduction
          - id: docs/get-mobi-css
          - id: docs/plugins-and-themes
      - id: docs/built-in-plugins
        sub_menu:
          - id: docs/reset
          - id: docs/top-gap
          - id: docs/show-hide-on-mobile
          - id: docs/flexbox
          - id: docs/container
          - id: docs/button
          - id: docs/form
          - id: docs/scroll-view
          - id: docs/table
          - id: docs/text
      - id: docs/customize
        sub_menu:
          - id: docs/build-tools
          - id: docs/variables
          - id: docs/create-a-plugin
          - id: docs/create-a-theme
  - id: plugins
  - id: themes
  - id: about
    menu:
      - id: about/index
        sub_menu:
          - id: about/community
          - id: about/support


plugins:
  - title: Reset
    description: Reset styles makes browsers render all elements more consistently.
    link: /docs/reset.html
  - title: Top Gap
    description: Set top gaps between block elements.
    link: /docs/top-gap.html
  - title: Show Hide on Mobile
    description: Show or hide an element on mobile.
    link: /docs/show-hide-on-mobile.html
  - title: Flexbox
    description: Use flexbox to layout.
    link: /docs/flexbox.html
  - title: Container
    description: The container plugin for Mobi.css
    link: /docs/container.html
  - title: Button
    description: The button plugin for Mobi.css
    link: /docs/button.html
  - title: Form
    description: The form plugin for Mobi.css
    link: /docs/form.html
  - title: Scroll View
    description: Make a block element scrollable.
    link: /docs/scroll-view.html
  - title: Table
    description: The table plugin for Mobi.css
    link: /docs/table.html
  - title: Text
    description: Utilities to create aligned text or colored text.
    link: /docs/text.html
  - title: Color
    description: Add more colors to your website.
    link: https://github.com/mobi-css/mobi-plugin-color
  - title: Prism
    description: The styles for highlighter Prism.
    link: https://github.com/mobi-css/mobi-plugin-prism


themes:
  - title: Base
    description: The base theme for Mobi.css
    link: /docs/variables.html
  - title: Dark
    description: In the dark I see your smile.
    link: https://github.com/mobi-css/mobi-theme-dark