src_dir: src
public_dir: docs

nav:
  - text: Docs
    link: /docs
    current_check_prefix: docs
  - text: Plugins
    link: /plugins
    current_check_prefix: plugins
  - text: Themes
    link: /themes
    current_check_prefix: themes
  - text: Community
    link: /community
    current_check_prefix: community

docs_menu:
  - text: Getting Started
    link: /docs
    sub_menu:
      - text: Introduction
        link: /docs
        current_check_prefix: docs/index
      - text: Get Mobi.css
        link: /docs/get-mobi-css.html
        current_check_prefix: docs/get-mobi-css
      - text: Plugins and Themes
        link: /docs/plugins-and-themes.html
        current_check_prefix: docs/plugins-and-themes
  - text: Built-in Plugins
    link: /docs/reset.html
    sub_menu:
      - text: Reset
        link: /docs/reset.html
        current_check_prefix: docs/reset
      - text: Top Gap
        link: /docs/top-gap.html
        current_check_prefix: docs/top-gap
      - text: Show Hide on Mobile
        link: /docs/show-hide-on-mobile.html
        current_check_prefix: docs/show-hide-on-mobile
      - text: Flexbox
        link: /docs/flexbox.html
        current_check_prefix: docs/flexbox
      - text: Container
        link: /docs/container.html
        current_check_prefix: docs/container
      - text: Button
        link: /docs/button.html
        current_check_prefix: docs/button
      - text: Form
        link: /docs/form.html
        current_check_prefix: docs/form
      - text: Scroll View
        link: /docs/scroll-view.html
        current_check_prefix: docs/scroll-view
      - text: Table
        link: /docs/table.html
        current_check_prefix: docs/table
      - text: Text
        link: /docs/text.html
        current_check_prefix: docs/text
  - text: Customize
    link: /docs/build-tools.html
    sub_menu:
      - text: Build Tools
        link: /docs/build-tools.html
        current_check_prefix: docs/build-tools
      - text: Variables
        link: /docs/variables.html
        current_check_prefix: docs/variables
      - text: Create a Plugin
        link: /docs/create-a-plugin.html
        current_check_prefix: docs/create-a-plugin
      - text: Create a Theme
        link: /docs/create-a-theme.html
        current_check_prefix: docs/create-a-theme

next:
  - current_check_prefix: index
    next_text: Introduction
    next_link: /docs
  - current_check_prefix: docs/index
    next_text: Get Mobi.css
    next_link: /docs/get-mobi-css.html
  - current_check_prefix: docs/get-mobi-css
    next_text: Plugins and Themes
    next_link: /docs/plugins-and-themes.html
  - current_check_prefix: docs/plugins-and-themes
    next_text: Reset
    next_link: /docs/reset.html
  - current_check_prefix: docs/reset
    next_text: Top Gap
    next_link: /docs/top-gap.html
  - current_check_prefix: docs/top-gap
    next_text: Show Hide on Mobile
    next_link: /docs/show-hide-on-mobile.html
  - current_check_prefix: docs/show-hide-on-mobile
    next_text: Flexbox
    next_link: /docs/flexbox.html
  - current_check_prefix: docs/flexbox
    next_text: Container
    next_link: /docs/container.html
  - current_check_prefix: docs/container
    next_text: Button
    next_link: /docs/button.html
  - current_check_prefix: docs/button
    next_text: Form
    next_link: /docs/form.html
  - current_check_prefix: docs/form
    next_text: Scroll View
    next_link: /docs/scroll-view.html
  - current_check_prefix: docs/scroll-view
    next_text: Table
    next_link: /docs/table.html
  - current_check_prefix: docs/table
    next_text: Text
    next_link: /docs/text.html
  - current_check_prefix: docs/text
    next_text: Build Tools
    next_link: /docs/build-tools.html
  - current_check_prefix: docs/build-tools
    next_text: Variables
    next_link: /docs/variables.html
  - current_check_prefix: docs/variables
    next_text: Create a Plugin
    next_link: /docs/create-a-plugin.html
  - current_check_prefix: docs/create-a-plugin
    next_text: Create a Theme
    next_link: /docs/create-a-theme.html
  - current_check_prefix: docs/create-a-theme
    next_text: Plugins
    next_link: /plugins
  - current_check_prefix: plugins
    next_text: Themes
    next_link: /themes
  - current_check_prefix: themes
    next_text: Community
    next_link: /community
  - current_check_prefix: community
    next_text: GitHub
    next_link: https://github.com/mobi-css/mobi.css

plugins:
  - title: Reset
    description: The reset styles that improved from Normalize.css with more suitability for mobile devices.
    docs: https://mobi-css.github.io/mobi-plugin-reset
    github: https://github.com/mobi-css/mobi-plugin-reset
    standalone: https://unpkg.com/mobi-plugin-reset/dist/mobi-plugin-reset.min.css
  - title: Top Gap
    description: Set top gaps between block elements.
    docs: https://mobi-css.github.io/mobi-plugin-top-gap
    github: https://github.com/mobi-css/mobi-plugin-top-gap
    standalone: https://unpkg.com/mobi-plugin-top-gap/dist/mobi-plugin-top-gap.min.css
  - title: Show Hide on Mobile
    description: Only show element on mobile or hide element on mobile.
    docs: https://mobi-css.github.io/mobi-plugin-show-hide-on-mobile
    github: https://github.com/mobi-css/mobi-plugin-show-hide-on-mobile
    standalone: https://unpkg.com/mobi-plugin-show-hide-on-mobile/dist/mobi-plugin-show-hide-on-mobile.min.css
  - title: Flexbox
    description: Use CSS3 flexbox to layout.
    docs: https://mobi-css.github.io/mobi-plugin-flexbox
    github: https://github.com/mobi-css/mobi-plugin-flexbox
    standalone: https://unpkg.com/mobi-plugin-flexbox/dist/mobi-plugin-flexbox.min.css
  - title: Container
    description: Three types of containers -- normal, wider and fluid.
    docs: https://mobi-css.github.io/mobi-plugin-container
    github: https://github.com/mobi-css/mobi-plugin-container
    standalone: https://unpkg.com/mobi-plugin-container/dist/mobi-plugin-container.min.css
  - title: Button
    description: Use buttons for actions in forms, dialogs, and more.
    docs: https://mobi-css.github.io/mobi-plugin-button
    github: https://github.com/mobi-css/mobi-plugin-button
    standalone: https://unpkg.com/mobi-plugin-button/dist/mobi-plugin-button.min.css
  - title: Form
    description: The form control styles.
    docs: https://mobi-css.github.io/mobi-plugin-form
    github: https://github.com/mobi-css/mobi-plugin-form
    standalone: https://unpkg.com/mobi-plugin-form/dist/mobi-plugin-form.min.css
  - title: Scroll View
    description: Make a block element scrollable.
    docs: https://mobi-css.github.io/mobi-plugin-scroll-view
    github: https://github.com/mobi-css/mobi-plugin-scroll-view
    standalone: https://unpkg.com/mobi-plugin-scroll-view/dist/mobi-plugin-scroll-view.min.css
  - title: Table
    description: The basic styles for table.
    docs: https://mobi-css.github.io/mobi-plugin-table
    github: https://github.com/mobi-css/mobi-plugin-table
    standalone: https://unpkg.com/mobi-plugin-table/dist/mobi-plugin-table.min.css
  - title: Text
    description: Utilities to create align text or colored text.
    docs: https://mobi-css.github.io/mobi-plugin-text
    github: https://github.com/mobi-css/mobi-plugin-text
    standalone: https://unpkg.com/mobi-plugin-text/dist/mobi-plugin-text.min.css
  - title: Color
    description: Add more colors to your website.
    docs: https://mobi-css.github.io/mobi-plugin-color
    github: https://github.com/mobi-css/mobi-plugin-color
    standalone: https://unpkg.com/mobi-plugin-color/dist/mobi-plugin-color.min.css
