favicon: /favicon.ico

menu:
  home:
    href: ''
    img: /assets/img/mobi-logo-512.png
  docs:
    href: docs
    icon: book
  reference:
    href: reference
    icon: hashtag
  extensions:
    href: extensions
    icon: cogs
  github:
    href: https://github.com/xcatliu/mobi.css
    icon: github
    align: right
